server:
  port: 8001
  servlet:
    context-path: "/runtime/"

spring:
  application:
    name: python-runtime

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: false

runtime:
  python-cmd: python
  max-time-limit: 10
