server:
  port: 8101
  servlet:
    context-path: "/runtime/"

spring:
  application:
    name: python-runtime

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

runtime:
  python-cmd: python
  max-time-limit: 10
