name: Test

on:
  push:
    branches:
      - dont

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup environment
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # build application using maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dspring.profiles.active=test verify